import { Injectable } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { ConfigService } from '@nestjs/config';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { firstValueFrom } from 'rxjs';
import { PluginResponse, EventBusService } from '../shared/event-bus.service';
import { Invoice } from '../invoice/entities/invoice.entity';

interface PluginHealthData {
  status: 'healthy' | 'unhealthy' | 'degraded';
  timestamp: string;
  metadata?: Record<string, any>;
}

@Injectable()
export class PluginWebhookService {
  private pluginOrchestrationUrl: string;

  constructor(
    private httpService: HttpService,
    private configService: ConfigService,
    private eventBusService: EventBusService,
    @InjectRepository(Invoice)
    private invoiceRepository: Repository<Invoice>,
  ) {
    this.pluginOrchestrationUrl =
      this.configService.get<string>('PLUGIN_ORCHESTRATION_URL') ||
      'http://localhost:3200';
  }

  async processPluginResponse(
    pluginId: string,
    response: PluginResponse,
    traceId?: string,
  ): Promise<void> {
    console.log(`Processing response from plugin ${pluginId}:`, response);

    // Handle successful plugin responses
    if (response.success) {
      await this.handleSuccessfulPluginResponse(pluginId, response, traceId);
    } else {
      await this.handleFailedPluginResponse(pluginId, response, traceId);
    }

    // Process any next events generated by the plugin
    if (response.nextEvents && response.nextEvents.length > 0) {
      for (const event of response.nextEvents) {
        await this.eventBusService.publishEvent(event);
      }
    }

    // Report plugin response to orchestration service
    await this.reportPluginResponse(pluginId, response, traceId);
  }

  private async handleSuccessfulPluginResponse(
    pluginId: string,
    response: PluginResponse,
    traceId?: string,
  ): Promise<void> {
    console.log(`Plugin ${pluginId} processed event successfully`);

    switch (pluginId) {
      case 'fiar':
        if (response.data?.creditTransaction) {
          console.log(
            `FIAR credit transaction created:`,
            response.data.creditTransaction,
          );
          // Update invoice with FIAR transaction reference if needed
          if (response.data.originalInvoice?.id) {
            await this.updateInvoiceWithPluginData(
              response.data.originalInvoice.id,
              { fiarTransactionId: response.data.creditTransaction.id },
            );
          }
        }
        break;

      case 'meravuelta':
        if (response.data?.deliveryOrder) {
          console.log(
            `MeraVuelta delivery order created:`,
            response.data.deliveryOrder,
          );
          // Update invoice with delivery order reference
          if (response.data.originalInvoice?.id) {
            await this.updateInvoiceWithPluginData(
              response.data.originalInvoice.id,
              { meraVueltaOrderId: response.data.deliveryOrder.id },
            );
          }
        }
        break;

      case 'graf':
        if (response.data?.orderStatus) {
          console.log(`Graf order status updated:`, response.data.orderStatus);
        }
        break;

      default:
        console.log(`Unknown plugin ${pluginId} response:`, response.data);
    }
  }

  private async handleFailedPluginResponse(
    pluginId: string,
    response: PluginResponse,
    traceId?: string,
  ): Promise<void> {
    console.error(
      `Plugin ${pluginId} failed to process event:`,
      response.error,
    );

    // TODO: Implement retry logic or dead letter queue
    // For now, just log the error
    await this.logPluginError(pluginId, response.error, traceId);
  }

  private async updateInvoiceWithPluginData(
    invoiceId: number,
    pluginData: Record<string, any>,
  ): Promise<void> {
    try {
      const invoice = await this.invoiceRepository.findOne({
        where: { id: invoiceId },
      });

      if (invoice) {
        // Store plugin data in a metadata field (you might need to add this field to the entity)
        const existingMetadata = (invoice as any).pluginMetadata || {};
        (invoice as any).pluginMetadata = {
          ...existingMetadata,
          ...pluginData,
        };

        await this.invoiceRepository.save(invoice);
        console.log(
          `Invoice ${invoiceId} updated with plugin data:`,
          pluginData,
        );
      }
    } catch (error) {
      console.error(
        `Failed to update invoice ${invoiceId} with plugin data:`,
        error,
      );
    }
  }

  private async logPluginError(
    pluginId: string,
    error: string,
    traceId?: string,
  ): Promise<void> {
    // TODO: Implement proper error logging/tracking
    console.error(`Plugin Error [${pluginId}] [${traceId}]:`, error);
  }

  private async reportPluginResponse(
    pluginId: string,
    response: PluginResponse,
    traceId?: string,
  ): Promise<void> {
    try {
      await firstValueFrom(
        this.httpService.post(
          `${this.pluginOrchestrationUrl}/plugins/${pluginId}/responses`,
          {
            response,
            traceId,
            timestamp: new Date().toISOString(),
          },
          {
            headers: {
              'Content-Type': 'application/json',
              'X-API-KEY': this.configService.get<string>(
                'PLUGIN_ORCHESTRATION_API_KEY',
              ),
            },
          },
        ),
      );
    } catch (error) {
      console.error(
        `Failed to report plugin response to orchestration service:`,
        error,
      );
    }
  }

  async updatePluginHealth(
    pluginId: string,
    healthData: PluginHealthData,
  ): Promise<void> {
    try {
      await firstValueFrom(
        this.httpService.post(
          `${this.pluginOrchestrationUrl}/plugins/${pluginId}/health`,
          healthData,
          {
            headers: {
              'Content-Type': 'application/json',
              'X-API-KEY': this.configService.get<string>(
                'PLUGIN_ORCHESTRATION_API_KEY',
              ),
            },
          },
        ),
      );
      console.log(`Plugin health updated for ${pluginId}:`, healthData.status);
    } catch (error) {
      console.error(`Failed to update plugin health for ${pluginId}:`, error);
    }
  }
}
